import type { Metadata } from "next";
import "./globals.css";
import { Kanit } from "next/font/google";

const font = Kanit({
  weight: "300",
  subsets: ["latin", "latin-ext", "thai", "vietnamese"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
